version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 project.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://user:password@db:5432/guessmaster
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_DB=guessmaster
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate
      - OLLAMA_MODEL=llama3
      - SECRET_KEY=your-secret-key-change-this-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    networks:
      - guessmaster_network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=guessmaster
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - guessmaster_network

  # Optional: Add pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - guessmaster_network

volumes:
  postgres_data:
  static_volume:

networks:
  guessmaster_network:
    driver: bridge
