version: '3.8'
services:
  web:
    build: .
    ports:
      - "${WEB_PORT:-9090}:9090"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    # Note: This assumes you have Ollama running on your host system
    # Configure OLLAMA_URL in your .env file to point to your Ollama instance
